from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from sqlalchemy import text
from backend.app.core.database import get_db
from pydantic import BaseModel

router = APIRouter()

class EmailRequest(BaseModel):
    site_id: str
    study_name: str

@router.post("/agent/draft-escalation")
def draft_escalation_email(request: EmailRequest, db: Session = Depends(get_db)):
    """
    AI Agent that looks at DB metrics for a specific site and drafts an email.
    """
    site_id = request.site_id
    study = request.study_name

    # 1. GATHER FACTS (The "Context" for the AI)
    # Get Missing Pages Count
    sql_missing = text("""
        SELECT COUNT(*) FROM raw_missing_pages 
        WHERE study_name = :study AND site_id = :site
    """)
    missing_count = db.execute(sql_missing, {"study": study, "site": site_id}).scalar() or 0

    # Get Protocol Deviations
    sql_pds = text("""
        SELECT pd_status, COUNT(*) 
        FROM raw_protocol_deviations 
        WHERE study_name = :study AND site_id = :site
        GROUP BY pd_status
    """)
    pd_rows = db.execute(sql_pds, {"study": study, "site": site_id}).fetchall()
    pd_summary = ", ".join([f"{row[1]} {row[0]}" for row in pd_rows]) or "None"

    # 2. GENERATE CONTENT (The "LLM" Logic)
    # If you have an OpenAI Key, you would pass 'context' to GPT-4 here.
    # For now, we use a "Logic Template" which is faster and free.
    
    subject_line = f"URGENT: Data Quality Escalation - {study} - {site_id}"
    
    risk_level = "HIGH" if missing_count > 20 else "MEDIUM"
    
    body = f"""Dear Site Monitor,

An automated review of {study} has identified critical data quality risks at {site_id}.
This site is currently flagged as {risk_level} RISK based on the following indicators:

1. MISSING CRITICAL DATA:
   - There are currently {missing_count} outstanding missing pages.
   - This exceeds the acceptable threshold of 10 pages per site.

2. PROTOCOL COMPLIANCE:
   - The following deviations have been recorded: {pd_summary}.

ACTION REQUIRED:
Please contact the site coordinator immediately to establish a timeline for data entry. 
If these issues are not resolved within 5 business days, this site may be placed on enrollment hold.

Generated by Clarity AI
    """

    return {
        "site_id": site_id,
        "risk_level": risk_level,
        "generated_email": {
            "subject": subject_line,
            "body": body
        }
    }